// frontend/src/lib/components/FanChart.svelte
<script lang="ts">
  import { Chart, Svg, Axis, Area, Spline, Highlight, Tooltip } from "layerchart";
  import { scaleLinear } from "d3-scale";
  import type { MonteCarloResult } from "$api/retirement";
  import { formatCurrency } from "$api/monarch";

  let { result }: { result: MonteCarloResult } = $props();

  let rows = $derived(
    result.ages.map((age, i) => ({
      age,
      p5: result.percentiles.p5[i],
      p25: result.percentiles.p25[i],
      p50: result.percentiles.p50[i],
      p75: result.percentiles.p75[i],
      p95: result.percentiles.p95[i],
    })),
  );
</script>

<div class="h-80">
  <Chart
    data={rows}
    x="age"
    xScale={scaleLinear()}
    yScale={scaleLinear()}
    yDomain={[0, undefined]}
    yNice
    padding={{ left: 64, bottom: 28, top: 8, right: 16 }}
    tooltip={{ mode: "voronoi" }}
  >
    <Svg>
      <Axis placement="left" grid rule format={(v: number) => `${Math.round(v / 1000)}k`} />
      <Axis placement="bottom" rule />
      <!-- 5–95% outer band (lightest) -->
      <Area y0Accessor={(d: any) => d.p5} y1Accessor={(d: any) => d.p95} class="fill-slate-200" />
      <!-- 25–75% inner band (mid) -->
      <Area y0Accessor={(d: any) => d.p25} y1Accessor={(d: any) => d.p75} class="fill-slate-400/60" />
      <!-- Median line -->
      <Spline y="p50" class="stroke-ink stroke-2" />
      <Highlight points lines y="p50" />
    </Svg>
    <Tooltip.Root let:data>
      <Tooltip.Header>Age {data.age}</Tooltip.Header>
      <Tooltip.List>
        <Tooltip.Item label="p95" value={formatCurrency(data.p95)} />
        <Tooltip.Item label="p75" value={formatCurrency(data.p75)} />
        <Tooltip.Item label="Median" value={formatCurrency(data.p50)} />
        <Tooltip.Item label="p25" value={formatCurrency(data.p25)} />
        <Tooltip.Item label="p5" value={formatCurrency(data.p5)} />
      </Tooltip.List>
    </Tooltip.Root>
  </Chart>
</div>

// frontend/src/components/FanChart.tsx
import {
  Area,
  CartesianGrid,
  ComposedChart,
  Legend,
  Line,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { MonteCarloResult } from "@/api/retirement";
import { formatCurrency } from "@/api/monarch";

export function FanChart({ result }: { result: MonteCarloResult }) {
  const bands = result.percentiles;
  const rows = result.ages.map((age, i) => ({
    age,
    // Stacked areas: render as a transparent base + deltas so each band fills.
    base: bands.p5[i],
    band5to25: bands.p25[i] - bands.p5[i],
    band25to75: bands.p75[i] - bands.p25[i],
    band75to95: bands.p95[i] - bands.p75[i],
    p50: bands.p50[i],
  }));

  return (
    <div className="h-80">
      <ResponsiveContainer width="100%" height="100%">
        <ComposedChart data={rows} margin={{ top: 8, right: 16, bottom: 8, left: 8 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
          <XAxis dataKey="age" tick={{ fontSize: 12 }} />
          <YAxis
            tickFormatter={(v) => `${Math.round(v / 1000)}k`}
            tick={{ fontSize: 12 }}
            width={48}
          />
          <Tooltip
            formatter={(v: number, name) => [formatCurrency(v), name]}
            labelFormatter={(l) => `Age ${l}`}
          />
          <Legend />
          <Area
            dataKey="base"
            stackId="band"
            stroke="none"
            fill="transparent"
            name="p5"
            legendType="none"
            tooltipType="none"
          />
          <Area
            dataKey="band5to25"
            stackId="band"
            stroke="none"
            fill="#cbd5e1"
            name="5-25%"
          />
          <Area
            dataKey="band25to75"
            stackId="band"
            stroke="none"
            fill="#94a3b8"
            name="25-75%"
          />
          <Area
            dataKey="band75to95"
            stackId="band"
            stroke="none"
            fill="#cbd5e1"
            name="75-95%"
          />
          <Line
            dataKey="p50"
            stroke="#0b1220"
            strokeWidth={2}
            dot={false}
            name="Median"
          />
        </ComposedChart>
      </ResponsiveContainer>
    </div>
  );
}
