// frontend/src/components/ProjectionChart.tsx
import {
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { DeterministicProjection } from "@/api/retirement";
import { formatCurrency } from "@/api/monarch";

export function ProjectionChart({ data }: { data: DeterministicProjection }) {
  const rows = data.ages.map((age, i) => ({
    age,
    balance: data.balance_real[i],
  }));
  return (
    <div className="h-80">
      <ResponsiveContainer width="100%" height="100%">
        <LineChart data={rows} margin={{ top: 8, right: 16, bottom: 8, left: 8 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
          <XAxis dataKey="age" tick={{ fontSize: 12 }} />
          <YAxis
            tickFormatter={(v) => `${Math.round(v / 1000)}k`}
            tick={{ fontSize: 12 }}
            width={48}
          />
          <Tooltip
            formatter={(v: number) => formatCurrency(v)}
            labelFormatter={(l) => `Age ${l}`}
          />
          <Line
            type="monotone"
            dataKey="balance"
            stroke="#0b1220"
            strokeWidth={2}
            dot={false}
          />
        </LineChart>
      </ResponsiveContainer>
    </div>
  );
}

// frontend/src/lib/components/ProjectionChart.svelte
<script lang="ts">
  import { Chart, Svg, Axis, Spline, Highlight, Tooltip } from "layerchart";
  import { scaleLinear } from "d3-scale";
  import type { DeterministicProjection } from "$api/retirement";
  import { formatCurrency } from "$api/monarch";

  let { data }: { data: DeterministicProjection } = $props();

  let rows = $derived(
    data.ages.map((age, i) => ({ age, balance: data.balance_real[i] })),
  );
</script>

<div class="h-80">
  <Chart
    data={rows}
    x="age"
    y="balance"
    xScale={scaleLinear()}
    yScale={scaleLinear()}
    padding={{ left: 64, bottom: 28, top: 8, right: 16 }}
    tooltip={{ mode: "voronoi" }}
  >
    <Svg>
      <Axis placement="left" grid rule format={(v: number) => `${Math.round(v / 1000)}k`} />
      <Axis placement="bottom" rule />
      <Spline class="stroke-ink stroke-2" />
      <Highlight points lines />
    </Svg>
    <Tooltip.Root let:data>
      <Tooltip.Header>Age {data.age}</Tooltip.Header>
      <Tooltip.List>
        <Tooltip.Item label="Balance" value={formatCurrency(data.balance)} />
      </Tooltip.List>
    </Tooltip.Root>
  </Chart>
</div>
